/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package app;

/**
 *
 * @author lfcsg
 */
public class Tela_Inicial extends javax.swing.JFrame {

    /**
     * Creates new form Tela_Inicial
     */
    public Tela_Inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JLLogin = new javax.swing.JLabel();
        JTLogin = new javax.swing.JTextField();
        JLSenha = new javax.swing.JLabel();
        JTSenha = new javax.swing.JTextField();
        JBEntrar = new javax.swing.JButton();
        JBSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela Login");
        setMinimumSize(new java.awt.Dimension(500, 300));
        getContentPane().setLayout(null);

        JLLogin.setText("Login");
        getContentPane().add(JLLogin);
        JLLogin.setBounds(160, 120, 30, 16);

        JTLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTLoginActionPerformed(evt);
            }
        });
        getContentPane().add(JTLogin);
        JTLogin.setBounds(200, 120, 200, 22);

        JLSenha.setText("Senha");
        getContentPane().add(JLSenha);
        JLSenha.setBounds(160, 160, 32, 16);
        getContentPane().add(JTSenha);
        JTSenha.setBounds(200, 160, 200, 22);

        JBEntrar.setText("Entrar");
        getContentPane().add(JBEntrar);
        JBEntrar.setBounds(330, 190, 72, 23);

        JBSair.setText("Sair");
        getContentPane().add(JBSair);
        JBSair.setBounds(240, 190, 72, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/mecainco.jpg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-140, -130, 760, 580);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JTLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBEntrar;
    private javax.swing.JButton JBSair;
    private javax.swing.JLabel JLLogin;
    private javax.swing.JLabel JLSenha;
    private javax.swing.JTextField JTLogin;
    private javax.swing.JTextField JTSenha;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
